server:
  port: 8085

spring:
  application:
    name: authentification-service

eureka:
  client:
    service-url:
      defaultZone: http://service-eureka:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: maCleSecreteTr√®sLongueEtComplexe12345
  expirationMs: 3600000